version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Tests
          command: |
            npm run lint
            npm run test:coverage && ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
